"""initial_schema

Revision ID: 69b0b4472e7b
Revises: 
Create Date: 2026-05-29 06:06:11.863770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b0b4472e7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_activity_type'), 'activity_logs', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('jobs_scraped', sa.Integer(), nullable=True),
    sa.Column('jobs_scored', sa.Integer(), nullable=True),
    sa.Column('applications_submitted', sa.Integer(), nullable=True),
    sa.Column('applications_viewed', sa.Integer(), nullable=True),
    sa.Column('interviews_scheduled', sa.Integer(), nullable=True),
    sa.Column('offers_received', sa.Integer(), nullable=True),
    sa.Column('application_success_rate', sa.Float(), nullable=True),
    sa.Column('interview_rate', sa.Float(), nullable=True),
    sa.Column('offer_rate', sa.Float(), nullable=True),
    sa.Column('platform_stats', sa.JSON(), nullable=True),
    sa.Column('best_resume_variant', sa.String(length=50), nullable=True),
    sa.Column('avg_ats_score', sa.Float(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('llm_api_calls', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_date'), 'analytics', ['date'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_job_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('hybrid', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'SCORED', 'APPLIED', 'REJECTED', name='jobstatus'), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.Column('company_info', sa.JSON(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_job_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_jobs_applied'), 'jobs', ['applied'], unique=False)
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_platform'), 'jobs', ['platform'], unique=False)
    op.create_index(op.f('ix_jobs_remote'), 'jobs', ['remote'], unique=False)
    op.create_index(op.f('ix_jobs_scraped_at'), 'jobs', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('portfolio_url', sa.Text(), nullable=True),
    sa.Column('target_roles', sa.JSON(), nullable=True),
    sa.Column('skills_primary', sa.JSON(), nullable=True),
    sa.Column('skills_secondary', sa.JSON(), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('willing_to_relocate', sa.JSON(), nullable=True),
    sa.Column('remote_preference', sa.String(length=50), nullable=True),
    sa.Column('minimum_salary_usd', sa.Integer(), nullable=True),
    sa.Column('minimum_salary_inr', sa.Integer(), nullable=True),
    sa.Column('currency_preference', sa.String(length=10), nullable=True),
    sa.Column('work_authorization', sa.JSON(), nullable=True),
    sa.Column('visa_sponsorship_required', sa.Boolean(), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('company_size_pref', sa.JSON(), nullable=True),
    sa.Column('company_stage_pref', sa.JSON(), nullable=True),
    sa.Column('base_resume_path', sa.Text(), nullable=True),
    sa.Column('base_cover_letter_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('target_roles', sa.JSON(), nullable=True),
    sa.Column('remote_preference', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('resume_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_resume_text', sa.Text(), nullable=False),
    sa.Column('tailored_resume_text', sa.Text(), nullable=False),
    sa.Column('resume_file_path', sa.Text(), nullable=True),
    sa.Column('variant_type', sa.String(length=50), nullable=True),
    sa.Column('keywords_added', sa.JSON(), nullable=True),
    sa.Column('keywords_removed', sa.JSON(), nullable=True),
    sa.Column('changes_made', sa.JSON(), nullable=True),
    sa.Column('ats_score_estimate', sa.Float(), nullable=True),
    sa.Column('keyword_density', sa.Float(), nullable=True),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_for_job_id', sa.UUID(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('viewed_count', sa.Integer(), nullable=True),
    sa.Column('interview_count', sa.Integer(), nullable=True),
    sa.Column('offer_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['created_for_job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_created_at'), 'resume_versions', ['created_at'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('variant', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('keyword_match', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_created_at'), 'resumes', ['created_at'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('resume_version_id', sa.UUID(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_application_id', sa.String(length=255), nullable=True),
    sa.Column('resume_path', sa.Text(), nullable=True),
    sa.Column('cover_letter_text', sa.Text(), nullable=True),
    sa.Column('cover_letter_path', sa.Text(), nullable=True),
    sa.Column('screening_questions', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'VIEWED', 'INTERVIEWING', 'REJECTED', 'OFFER', 'ACCEPTED', 'DECLINED', name='applicationstatus'), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('interview_date', sa.DateTime(), nullable=True),
    sa.Column('interview_type', sa.String(length=50), nullable=True),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.Column('offer_received', sa.Boolean(), nullable=True),
    sa.Column('offer_amount', sa.Integer(), nullable=True),
    sa.Column('offer_currency', sa.String(length=10), nullable=True),
    sa.Column('offer_date', sa.DateTime(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('confirmation_email', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submission_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_applied_at'), 'applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_platform'), 'applications', ['platform'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_platform'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_applied_at'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_created_at'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_resume_versions_created_at'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_scraped_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_remote'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_platform'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_applied'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_analytics_date'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
